config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'

  get 'translate' => "welcome#translate", as: :translate
  resources :books do
    resources :chapters, only: [:create, :edit, :update, :destroy] do
      resources :sections, only: [:create, :edit, :show, :update, :destroy]
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  validates :title, presence: true
  
  def sorted_chapter_ids=(ids_array)
    ids_array = JSON.parse(ids_array)
    grouped_chapters = self.chapters.where(id: ids_array).group_by(&:id)
    index_no = 1
    ids_array.each do |chapter_id|
      chapter_id = chapter_id.to_i
      chapter = grouped_chapters[chapter_id][0]
      chapter.update_attribute(:position, index_no)

      index_no += 1
    end
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :sections
  belongs_to :book
  validates :title, presence: true

  before_create :set_position

   default_scope {order(position: :asc)}

  def sorted_section_ids=(ids_array)
    ids_array = JSON.parse(ids_array)
    grouped_sections = self.sections.where(id: ids_array).group_by(&:id)
    index_no = 1
    ids_array.each do |section_id|
      section_id = section_id.to_i
      section = grouped_sections[section_id][0]
      section.update_attribute(:position, index_no)

      index_no += 1
    end
  end

   private

   def set_position
     self.position = (self.book.chapters[-2].try(:position) || 0) + 1
   end

end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter, dependent: :destroy
  validates :title, presence: true

  before_create :set_position

  default_scope {order(position: :asc)}

  private

   def set_position
     self.position = (self.chapter.sections[-2].try(:position) || 0) + 1
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :fetch_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    if @book.save
      flash[:success] = I18n.t('flash_msgs.books.creation_success')
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes(book_params)
      if params[:book][:sorted_chapter_ids]
        render nothing: true
      else
        flash[:success] = I18n.t('flash_msgs.books.updation_success')
        redirect_to book_path(@book) 
      end
    else
      render :edit
    end
  end

  def show
    @chapters = @book.chapters.includes(:sections).all
    @new_chapter = @book.chapters.new
    @new_sections = {}
    @chapters.each do |chapter|
      @new_sections[chapter.id] = chapter.sections.new
    end
  end

  def destroy
    if params[:title_confirmation].downcase == @book.title.downcase
      @book.destroy
      flash[:success] = i18n.t('flash_msgs.books.deletion_success')
      redirect_to books_path
    else
      flash[:danger] = i18n.t('flash_msgs.books.deletion_failure')
      redirect_to book_path(@book)
    end
  end

  private
  def fetch_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :notes, :sorted_chapter_ids)
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :fetch_book
  before_action :fetch_chapter, only: [:edit, :update, :destroy]

  def create
    @chapter = @book.chapters.new(chapter_params)
    @save_success = !!@chapter.save
    @new_sections = { @chapter.id => @chapter.sections.new }
  end

  def edit
  end

  def update
    if @chapter.update_attributes(chapter_params)
      if params[:chapter][:sorted_section_ids]
        debugger
        render nothing: true
      else
        @chapter.reload unless @chapter.valid?
        @new_sections = { @chapter.id => @chapter.sections.new }
      end
    end
  end

  def destroy
    if @chapter.sections.any?
      flash.now[:danger] = I18n.t('flash_msgs.chapters.deletion_failure')
      @destroy_failure = true
    else
      @chapter.destroy
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:title, :notes, :sorted_section_ids)
  end

  def fetch_book
    @book = Book.find(params[:book_id])
  end

  def fetch_chapter
    @chapter = @book.chapters.find(params[:id])
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :fetch_chapter
  before_action :fetch_section, only: [:show, :update, :destroy, :edit]

  def create
    @section = @chapter.sections.new(section_params)
    @save_success = @section.save
  end

  def edit
  end

  def show
  end

  def update
    @section.update_attributes(section_params)
  end

  def destroy
    if params[:title_confirmation].downcase == @section.title.downcase
      @destroy_success = true
      @section.destroy
      flash.now[:success] = I18n.t('flash_msgs.sections.deletion_success')
    else
      flash.now[:danger] = I18n.t('flash_msgs.sections.deletion_failure')
    end 
  end 

  private
  def fetch_chapter
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.find(params[:chapter_id])
  end

  def section_params
    params.require(:section).permit(:title, :notes, :content)
  end

  def fetch_section
    @section = @chapter.sections.find(params[:id])
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :translate]
  
  def index
  end

  def translate
    I18n.locale = params[:locale].to_sym
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def landing_page?
    controller_name == 'welcome' && action_name == 'index'
  end
  
  def flash_messages_tag
    str = ""

    flash.each do |fl|
      fl[0] = "success" if fl[0] == "notice"
      fl[0] = "danger" if fl[0] == "error" || fl[0] == "alert"
      str += content_tag(:div, class: "alert alert-#{fl[0]}") do
        content_tag(:button, class: "close", data: {dismiss: "alert"}) do
          content_tag(:span, raw("&times;"))
        end + fl[1]
      end
    end

    return raw(str)
  end
  
  def refresh_flash_message
    raw "BookMakerUtils.showFlash('#{j flash_messages_tag}');"
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
<%= f.input :title %>
<%= f.input :notes%>
<%= f.button :submit, class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/books/edit.html.erb
  <h1>Edit <%= @book.title %></h1>
  <%= render 'books/form' %>

app/views/books/index.html.erb
<div class="container-fluid">
<%= link_to "Add new Book", new_book_path, class: "btn btn-success pull-right" %>
<h1>Choose a book to contribute to</h1>
</div>
<div class="container-fluid">
  <div class="row" id="books">
    <% @books.each do |book| %>
      <div class="col-md-4 book">
        <div class="well">
          <h3><%= link_to book.title, book_path(book) %></h3>
          <p><%= book.notes %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<h1>Add New Book</h1>
<%= render 'books/form' %>

app/views/books/show.html.erb
<section id="book" class="row" data-book-id="<%= @book.id %>">
  <div id="book-content" class="col-md-8 col-md-push-4">

    <%= link_to fa_icon('trash', text:"Delete"),"#", class: "btn btn-danger pull-right", data: {toggle: "modal", target: "#delete-confirmation-modal"} %>

    <%= link_to fa_icon('pencil', text: "Edit"), edit_book_path(@book), class: "btn btn-primary pull-right" %>
    <h1><%= @book.title %></h1>
    <p><%= @book.notes %></p>
    <div id="section-content">
    </div>
  </div>
  <div id="sidebar" class="col-md-4 col-md-pull-8">

    <div id="chapters-list">
      <%= render @chapters %>
    </div>
    <%= link_to "+ Add New Chapter", '#',id: 'trigger-new-chapter-form' %> 

    <%= render partial: 'chapters/form', locals: {chapter: @new_chapter} %>
  </div>
</section>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="delete-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirm Delete? </h4>
      </div>
      <div class="modal-body">
        <p>
        Are you sure you want to delete the book and all its content? If yes, please type in the title of the book below and submit.
        </p>

        <%= form_tag(book_path(@book), method: :delete) do %>

          <div class="form-group">
            <%= text_field_tag(:title_confirmation, "", type: "text", class: "form-control") %>
          </div>
          <%= submit_tag("Confirm", class: "btn btn-danger") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/chapters/_chapter.html.erb
<div id="<%= dom_id chapter %>" class="chapter clearfix"> <%= link_to fa_icon('trash'), book_chapter_path(chapter.book, chapter), remote: true, method: :delete, class: "text-danger chapter-delete", data: {confirm: "Are you sure you want to delete the chapter titled: #{chapter.title}? This is irreversible"} %>
<%= link_to fa_icon('pencil'), edit_book_chapter_path(chapter.book, chapter), remote: true, class: "chapter-edit" %>
<%= fa_icon 'bars' %>
  <%= link_to "#", class: "chapter-title", remote: true do %>
    <%= fa_icon 'caret-right' %>
    <%= fa_icon 'caret-down' %>
    <%= chapter.title %>
  <% end %>
<div class="sections">
  <div class="sections-list" data-chapter-id="<%= chapter.id %>">
    <%= render chapter.sections %>
  </div>
    <%= link_to "+ Add Section", "#", data: {toggle: "modal", target: "#new-section-modal-#{chapter.id}"} %>
</div>
</div>

<!-- New Section Modal -->
<div class="modal fade" id="new-section-modal-<%= chapter.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Section to <%= chapter.title %></h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-danger hidden" role="alert">
          <%= t 'flash_messages.sections.creation_failure' %>
        </div>
        <%= simple_form_for [chapter.book, chapter, @new_sections[chapter.id]], remote: true do |f| %>
          <%= f.input :title %>
          <%= f.input :notes %>
          <%= f.submit class: "btn btn-primary" %>
        <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/chapters/_edit_modal.html.erb
<div id="edit-chapter-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit Chapter</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'chapters/form', locals: {chapter: @chapter} %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/chapters/_form.html.erb
<%= simple_form_for [chapter.book, chapter], html: {id: "new-chapter-form"}, remote: true do |f| %>
  <%= f.input :title %>
  <%= f.input :notes %>
  <%= f.submit class: "btn btn-primary btn" %>
  <%= link_to("Cancel", "#", id: "cancel-chapter-form") if chapter.new_record? %>
<% end %>

app/views/chapters/create.js.erb
<% if @save_success %>
  ChapterUtils.hideNewChapterForm();
  $('#new-chapter-form')[0].reset();
  $('#chapters-list').append('<%= j render(@chapter) %>');
<% else %>
  $('#new-chapter-form').replaceWith('<%= j render(partial: "chapters/form", locals: {chapter: @chapter}) %>');
  ChapterUtils.bindNewChapterCancelLink();
<% end %>

app/views/chapters/destroy.js.erb
<% if @destroy_failure %>
  <%= refresh_flash_message %>
<% else %>
  $('#<%= dom_id(@chapter) %>').remove();
<% end %>

app/views/chapters/edit.js.erb
$('#edit-chapter-modal').remove();
$('body').append('<%= j render("chapters/edit_modal") %>');
$('#edit-chapter-modal').modal('show');

app/views/chapters/update.js.erb
$('#edit-chapter-modal').modal('hide');
$('#<%= dom_id @chapter %>').replaceWith('<%= j render(@chapter) %>');

app/views/common/_footer.html.erb
<footer class="container">
  <nav class="container-fluid navbar navbar-fixed-bottom">
    Choose Language: <%= link_to "en", translate_path(locale: :en) %> |
    <%= link_to "hi", translate_path(locale: :hi) %>
  </nav>
</footer>

app/views/common/_header.html.erb
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to APP_NAME, root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to current_user.email, destroy_user_session_path(current_user), method: :delete %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:200,400,400italic,600' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'common/header' unless landing_page? %>
  <%= flash_messages_tag %>
  <div class="<%= 'container' unless landing_page? %>">
<%= yield %>
  </div>
  <%= render 'common/footer' unless landing_page? %>
</body>
</html>

app/views/sections/_edit_modal.html.erb
<div id="edit-section-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit section</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'sections/form', locals: {section: @section} %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/sections/_form.html.erb
<%= simple_form_for [@book, @chapter, @section ], remote: true do |f| %>
          <%= f.input :title %>
          <%= f.input :notes %>
          <%= f.submit class: "btn btn-primary" %>
<% end %> 

app/views/sections/_section.html.erb
<% unless section.new_record? %>
  <div id="<%= dom_id section %>" class="section clearfix" data-section-id="<%= section.id %>">
    <%= fa_icon 'bars', class: 'forsection' %>
    <%= link_to section.title, book_chapter_section_path(section.chapter.book, section.chapter, section), class: "section-title", remote: true %>
  </div>
<% end %>

app/views/sections/_section_content.html.erb
<%= render 'sections/section_header' %>
<div id="editform">
<%= render 'sections/form' %>
</div>

<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#section-preview" aria-controls="home" role="tab" data-toggle="tab">Preview</a></li>
    <li role="presentation"><a href="#section-edit" aria-controls="profile" role="tab" data-toggle="tab">Edit</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="section-preview">
      <%= render 'sections/section_preview' %>
    </div>
    <div role="tabpanel" class="tab-pane" id="section-edit">
      <%= simple_form_for [@book, @chapter, @section], remote: true do |f| %>
        <%= f.input :content %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="section-delete-confirmation-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirm Delete? </h4>
      </div>
      <div class="modal-body">
        <p>
        Are you sure you want to delete the section and all its content? If yes, please type in the title of the section below and submit.
        </p>

        <%= form_tag(book_chapter_section_path(@book, @chapter, @section), method: :delete, remote:true) do %>

          <div class="form-group">
            <%= text_field_tag(:title_confirmation, "", type: "text", class: "form-control") %>
          </div>
          <%= submit_tag("Confirm", class: "btn btn-danger") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sections/_section_header.html.erb
<div id="<%= dom_id @section %>">
<h2>
  <%= @section.title %>
  <small>
    <em>in</em>
    <%= @chapter.title %>
    <%= link_to fa_icon('pencil'), edit_book_chapter_section_path(@book, @chapter, @section), class: "text-primary", remote: true %>
    <%= link_to fa_icon('trash'), "#", class: "text-danger", data: {toggle: "modal", target: "#section-delete-confirmation-modal"} %>
  </small>
</h2>
<p>
<%= @section.notes %>
</p>
</div>

app/views/sections/_section_preview.html.erb
<p>
  <%= @section.content %>
</p>

app/views/sections/create.js.erb
<% if @save_success %>
  $('#new-section-modal-<%= @chapter.id %> .alert').addClass('hidden');
  $('#new-section-modal-<%= @chapter.id %> form')[0].reset();
  $('#new-section-modal-<%= @chapter.id %>').modal('hide');
  $('#<%= dom_id(@chapter) %> .sections-list').append('<%= j render(@section) %>');
<% else %>
  $('#new-section-modal-<%= @chapter.id %> .alert').removeClass('hidden');
<% end %>

app/views/sections/destroy.js.erb
$('#section-delete-confirmation-modal').modal('hide');
<% if @destroy_success %>
  setTimeout(function() {
    $('#section-content').html('')
  }, 500);
  $('#sidebar .sections-list #<%= dom_id(@section) %>').remove();
<% end %>
<%= refresh_flash_message %>

app/views/sections/edit.js.erb
$('#<%= dom_id @section %>').hide()
$('#editform').show()

app/views/sections/show.js.erb
$('#section-content').html('<%= j render("sections/section_content") %>');

app/views/sections/update.js.erb
$('a[href="#section-preview"]').tab('show');
$('#section-preview').html('<%= j render("sections/section_preview") %>');
$('#editform').hide()
$('#<%= dom_id @section %>').replaceWith('<%= j render("sections/section_header") %>')

app/views/welcome/index.html.erb
<div id="land">
  <div class="vcenter">
    <h1>Put your thoughts in words</h1>
    <%= link_to "Get Started", books_path, class: "btn btn-outline btn-lg" %>
  </div>
</div>